notifications:
    slack: designproject2018:rhfcpmTwX4UsvhNJ9jxyJ1P0

language: node_js

before_script:
- sudo apt-get update
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get -y install nodejs 
- sudo apt-get install -y build-essential
- sudo apt-get clean
- sudo npm install -g cordova ionic 
- sudo npm install --no-bin-links
- sudo ionic build
